language: go
sudo: false
go:
    - tip
service:
    - postgresql
before_install:
before_script:
    - psql -c 'create database test;' -U test
    - psql -c 'create table test (domain varchar (253) NOT NULL,cert_raw bytea NOT NULL);' -U test 
notifications:
    email:
        on_success: never
        on_failure: always
script:
    - go test -v ./...
