language: go
sudo: false
go:
    - tip
service:
    - postgresql
before_install:
before_script:
    - psql -c 'create database test;' -U postgres 
    - psql -c 'create user test;' -U postgres
notifications:
    email:
        on_success: never
        on_failure: always
script:
    - go test -v ./...
