language: go
sudo: false
go:
    - tip
before_install:
    - go install github.com/mattn/goveralls
before_script:
notifications:
    email:
        on_success: never
        on_failure: always
script:
    - $HOME/gopath/bin/goveralls -service=travis-pro
